val_cols <- c("AT val",
              "MD val",
              "Con val",
              "Dams val",
              "SMR val",
              "SNR val")

suit_cols <- c("AT suit",
               "MD suit",
               "Con suit",
               "Dams suit",
               "SMR suit",
               "SNR suit")

ESC_spp_v1 <- c("Abies alba", 
                "Abies amabilis", 
                "Abies grandis",              
                "Abies nordmanniana", 
                "Abies procera", 
                "Acer macrophyllum",         
                "Acer platanoides", 
                "Acer pseudoplatanus", 
                "Alnus cordata",             
                "Alnus glutinosa", 
                "Alnus incana", 
                "Alnus rubra",               
                "Betula pendula", 
                "Betula pubescens", 
                "Carpinus betulus",          
                "Castanea sativa", 
                "Chamaecyparis lawsoniana", 
                "Cryptomeria japonica",      
                "Cupressocyparis x leyandii", 
                "Eucalyptus gunnii", 
                "Euclayptus nitens",         
                "Fagus sylvatica", 
                "Fraxinus excelsior", 
                "Juglans nigra",             
                "Juglans regia", 
                "Larix decidua", 
                "Larix eurolepsis",          
                "Larix kaempferi", 
                "Nothofagus obliqua",        
                "Nothofagus procera", 
                "Picea abies", 
                "Picea omorika",             
                "Picea orientalis", 
                "Picea sitchensis", 
                "Pinus contorta",            
                "Pinus nigra ssp. Laricio", 
                "Pinus peuce", 
                "Pinus pinaster",            
                "Pinus radiata", 
                "Pinus strobus", 
                "Pinus sylvestris",          
                "Populus nigra", 
                "Populus tremula", 
                "Prunus avium",              
                "Pseudotsuga menziesii", 
                "Quercus petraea", 
                "Quercus robur",             
                "Quercus rubra", 
                "Sequoia sempervirens", 
                "Sequoiadendron giganteum",  
                "Sorbus aucuparia", 
                "Sorbus domestica", 
                "Sorbus torminalis",         
                "Thuja plicata", 
                "Tilia cordata", 
                "Tsuga heterophyla",         
                "Ulmus glabra")

# ESC_spp_non_native <- c("Abies alba",
#                         "Abies amabilis",
#                         "Abies grandis",
#                         "Abies nordmanniana",
#                         "Abies procera",
#                         "Acer macrophyllum",
#                         "Acer platanoides",
#                         "Acer pseudoplatanus",
#                         "Alnus cordata",
#                         "Alnus glutinosa",
#                         "Alnus incana",
#                         "Alnus rubra",
#                         "Betula pendula",
#                         "Betula pubescens",
#                         "Carpinus betulus",
#                         "Castanea sativa",
#                         "Chamaecyparis lawsoniana",
#                         "Cryptomeria japonica",
#                         "Cupressocyparis x leyandii",
#                         "Eucalyptus gunnii",
#                         "Euclayptus nitens",
#                         "Fagus sylvatica",
#                         "Fraxinus excelsior",
#                         "Juglans nigra",
#                         "Juglans regia",
#                         "Larix decidua",
#                         "Larix eurolepsis",
#                         "Larix kaempferi",
#                         "Nothofagus obliqua",
#                         "Nothofagus procera",
#                         "Picea abies",
#                         "Picea omorika",
#                         "Picea orientalis",
#                         "Picea sitchensis",
#                         "Pinus contorta",
#                         "Pinus nigra ssp. Laricio",
#                         "Pinus peuce",
#                         "Pinus pinaster",
#                         "Pinus radiata",
#                         "Pinus strobus",
#                         "Pinus sylvestris",
#                         "Populus nigra",
#                         "Populus tremula",
#                         "Prunus avium",
#                         "Pseudotsuga menziesii",
#                         "Quercus petraea",
#                         "Quercus robur",
#                         "Quercus rubra",
#                         "Sequoia sempervirens",
#                         "Sequoiadendron giganteum",
#                         "Sorbus aucuparia",
#                         "Sorbus domestica",
#                         "Sorbus torminalis",
#                         "Thuja plicata",
#                         "Tilia cordata",
#                         "Tsuga heterophyla",
#                         "Ulmus glabra")

ESC_spp_add <- c("Acer campestre", 
                 "Buxus sempervirens", 
                 "Corylus avellana", 
                 "Cornus sanguinea", 
                 "Euonymus europaeus", 
                 "Ilex aquifolium", 
                 "Juniperus communis",
                 "Hippophae rhamnoides", 
                 "Arbutus unedo",
                 "Tilia platyphyllos", 
                 "Tilia x europaea",
                 "Ligustrum vulgare", 
                 "Frangula alnus",
                 "Rhamnus cathartica", 
                 "Crataegus laevigata",
                 "Crataegus monogyna",
                 "Malus sylvestris",
                 "Prunus padus",
                 "Prunus spinosa",
                 "Sorbus aria",
                 "Populus nigra subsp. betulifolia",
                 "Salix caprea",
                 "Salix cinerea",
                 "Salix pentandra",
                 "Salix phylicifolia",
                 "Taxus baccata",
                 "Ulmus minor")

ESC_spp_v2 <- c(ESC_spp_v1, ESC_spp_add)